name: 02 - Workflow Events

on:
  #   push:
  pull_request:
  #   schedule:
  #     - cron: "*/5 * * * *" # Runs at midnight UTC every day
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I've been triggered by ${{ github.event_name }} event."
