name: 03 - Workflow Runners

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show Ubuntu runner
        run: |
          echo "This job is running on $RUNNER_OS with $RUNNER_NAME."
