name: 04 - Using Actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app #This is used in the full steps.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Printing Folders
      #   run: ls
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
        #working-directory: 04-using-actions/react-app
      - name: Run Unit Tests
        run: npm run test #This is based on the package.json file in the react-app folder
        #working-directory: 04-using-actions/react-app

    # 0. Checkout the code from the repository
    # 1. Install dependencies
    # 2. Execute tests
