name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on:
  push:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      debug:
        description: "Enable debug mode"
        default: false
        type: boolean
env:
  MY_WORKFLOW_VAR: "Workflow"
  MY_OVERWRITTEN_VAR: "workflow"
jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "job"
      MY_OVERWRITTEN_VAR: "job"
    steps:
      - name: Display information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Reference: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
      - name: Retrieve Variable
        run: |
          echo "Variable value: ${{ vars.MY_VAR }}!"
      - name: Print Environment Variables
        env:
          MY_OVERWRITTEN_VAR: "step"
        run: |
          echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}
          echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}
      - name: Print Environment Variables
        run: |
          echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}"
          echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"
